# Generated by rust2rpm 27
%bcond check 1

# prevent library files from being installed
%global cargo_install_lib 0

Name:           lazy_format
Version:        2.0.3
Release:        %autorelease
Summary:        Utility crate for lazily formatting values for later

License:        MPL-2.0
# LICENSE.dependencies contains a full license breakdown

URL:            https://github.com/Lucretiel/lazy_format
Source:         %{url}/archive/refs/tags/%{version}.tar.gz

BuildRequires:  cargo-rpm-macros >= 26

%global _description %{expand:
A utility crate for lazily formatting values for later.}

%description %{_description}

%prep
%autosetup -n lazy_format-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license LICENSE.dependencies
%doc CHANGELOG.md
%doc README.md

%changelog
%autochangelog
